name: my_social_sdk
description: My Social SDK package
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  fdl_core:
    path: ../fdl_core
  fdl_types:
    path: ../fdl_types

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
