name: fdl_bloc
description: FDL Bloc utilities package
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  fdl_types:
    path: ../fdl_types

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mockito: ^5.4.4
  build_runner: ^2.7.0
