name: openapi_sdk_generator
description: Command-line tool to generate Flutter/Dart SDK from OpenAPI specification
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.1

executables:
  openapi-sdk-generator: openapi_sdk_generator

dependencies:
  http: ^1.2.0
  yaml: ^3.1.2
  path: ^1.9.0
  code_builder: ^4.11.0
  dart_style: ^3.1.3
  args: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
