name: fdl_core
description: FDL core package
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  fdl_types:
    path: ../fdl_types
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

